import Head from 'next/head'
import {Divider, Typography, Stack, LinearProgress, CircularProgress} from "@mui/material";
import {useTheme} from "@mui/material";
import BasePageComponents from "@/components/layouts/BasePageComponents";
import StandardContainer from "@/components/layouts/StandardContainer";
import Box from "@mui/material/Box";
import {useRouter} from "next/router";
import {pathToFavicon, redirectPath, siteTitle} from "@/config/appConfig";
import {useEffect} from "react";

interface HomeProps {
    readMeContent: string
}

const Home = (props: HomeProps) => {
    const theme  = useTheme();
    const router = useRouter();

    useEffect(() => {
        router.push(redirectPath)
    }, [router])

    return (
        <BasePageComponents>
            <Head>
                <title>{siteTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href={pathToFavicon} />
            </Head>
            <StandardContainer>

                    <CircularProgress size={50} sx={{color: theme.palette.action.active, position: `absolute`, top: `50%`, left: `50%`}} variant={'indeterminate'} />

            </StandardContainer>

        </BasePageComponents>
    )
}

export default Home;