import Head from 'next/head'
import {Divider, Typography, Stack} from "@mui/material";
import {useTheme} from "@mui/system";
import withAuth from "@/components/withAuth";
import BasePageComponents from "@/components/layouts/BasePageComponents";
import SlimContainer from "@/components/layouts/SlimContainer";
import StandardContainer from "@/components/layouts/StandardContainer";
import { readFileSync } from 'fs'
import Link from "next/link";



type HomeProps = {

}

const Home = (props: HomeProps) => {
    const theme  = useTheme();
    return (
        <BasePageComponents>
            <Head>
                <title>Web Starter Kit</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <StandardContainer>
                <Stack sx={{width: `100%`}}>
                    <Typography variant={'h1'} sx={{color: theme.palette.primary.main, fontFamily: `Poppins !important`}}> 👋 Web Starter Kit </Typography>
                    <Divider component="div" sx={{margin: theme.spacing(2), width: `100%`}}/>
                    <Link href={'/docs/getting-started'} passHref>Getting Started</Link>
                </Stack>
            </StandardContainer>

        </BasePageComponents>
    )
}


export default withAuth(Home);