
name: build-and-push-image
run-name: "build and push image (on-demand) (triggered by: ${{ github.actor }})"
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: set up environment
        run: |
          echo "sha_short=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "repo_name=$(echo ${{ github.repository }} | cut -d/ -f2)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        name: setup QEMU
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ubdc
          password: ${{ secrets.DOCKER_HUB_RW_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.UBDC_DOCKER_HUB_REPO }}/${{ env.repo_name }}:${{ env.sha_short }}